# Generated by Django 4.0.4 on 2022-06-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Cliente')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido Cliente')),
                ('telefono', models.IntegerField(verbose_name='Telefono Cliente')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo Cliente')),
                ('contraseña', models.CharField(max_length=12, verbose_name='Contraseña1')),
                ('scontraseña', models.CharField(max_length=12, verbose_name='Contraseña2')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo zapatilla')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('fotoProducto', models.ImageField(upload_to='zapatilla')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
            ],
        ),
    ]
