# Generated by Django 4.0.4 on 2022-06-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0002_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=40, verbose_name='Correo Cliente'),
        ),
    ]
