# Generated by Django 4.0.4 on 2022-06-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaOnline', '0003_alter_cliente_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre Producto')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
    ]
